### ISSUE TITLE
no createDate in Post?

### ISSUE THREAD

**Issue by nielinjie** [satoryu/metaweblog#1]
createDate is really useful when migration blogs. 
Please add. 
Thank you a lot.

**Comment by satoryu** [comment]
@nielinjie thank you for your request. 
This gem follows the specification of [metaWeblogAPI](http://xmlrpc.scripting.com/metaWeblogApi.html) and [RSS 2.0](http://cyber.law.harvard.edu/rss/rss.html#hrelementsOfLtitemgt) . 
I could not found 'createDate' but found 'pubDate' there. Is it right?
if no, please tell me information about 'createDate'.

**Comment by nielinjie** [comment]
Yes, you are right. 'pubDate' will be great. Thanks a lot.

**Comment by satoryu** [comment]
@nielinjie 

sorry for too late reply. 
I've released v0.2.0 of metaweblog 1910a6eb8130d6d6929eae859891c52b5c73085b . From this version, MetaWeblog::Post supports pubDate. 
Please try it!
